package com.fiap.soat.model.enums;

import lombok.Getter;

@Getter
public enum ServiceError {
  GENERIC_ERROR,
  CUSTOMER_CREATE_EXISTS_DOCUMENT_NUMBER,
  CUSTOMER_NOT_EXISTS,
  PRODUCT_NOT_EXISTS,
  ORDER_NOT_EXISTS,
  ORDER_PRODUCT_EXISTS_IN_LIST,
  ORDER_PRODUCT_NOT_EXISTS_IN_LIST,
  ORDER_STATUS_MUST_BE_CREATED,
  ORDER_STATUS_PAID_NOT_CANCEL,
  ORDER_STATUS_IS_ALREADY_CANCELLED,
  CHARGE_ORDER_STATUS_NOT_CREATED,
  CHARGE_ORDER_PRODUCTS_EMPTY,
  QUEUE_ENVOLVE_STATUS_FINISHED,
  QUEUE_NOT_FOUND,
  QUEUE_NOT_FIRST_PROCESS
}
